smoke

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -249,63 +249,94 @@ jobs:
       - destroy_environments:
             workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}   
 
+  # configure-infrastructure:
+  #   docker:
+  #     # Docker image here that supports Ansible
+  #     # - image: python:3.7-alpine3.16 
+  #     # - image: python:3.9.1-alpine3.12  
+  #     - image: python:3.11-rc-alpine  
+  #   steps:
+  #     # Checkout code from git
+  #     # Add ssh keys with fingerprint
+  #     # attach workspace
+  #     - checkout
+  #     - add_ssh_keys:
+  #         fingerprints: ["a3:c0:12:e5:23:e7:fa:23:10:a5:d9:ae:b6:99:35:80"] 
+          
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           # Your code here
+  #           # apk add tar gzip 
+  #           # apk add --update ansible aws-cli
+  #           # apk add --update --no-cache tar gzip ansible awscli
+  #           # apk add --update tar gzip ansible
+  #           # pip install awscli
+  #           apk update 
+  #           apk upgrade
+  #           apk add --update ansible
+  #           apk --no-cache add python3 py3-pip
+  #           pip3 install --upgrade pip
+  #           pip3 install --no-cache-dir awscli
+  #           #exit 1
+            
+  #     - run:
+  #         name: Configure server
+  #         command: |
+  #           # Your code here
+  #           echo NODE_ENV=production > ~/project/backend/.env
+  #           echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> ~/project/backend/.env
+  #           echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ~/project/backend/.env
+  #           echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> ~/project/backend/.env
+  #           echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> ~/project/backend/.env
+  #           echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> ~/project/backend/.env
+  #           echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ~/project/backend/.env
+  #           echo TYPEORM_PORT=$TYPEORM_PORT >> ~/project/backend/.env
+  #           echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ~/project/backend/.env
+  #           cat ~/project/backend/.env
+
+  #           cd ~/project/.circleci/ansible
+  #           ansible-playbook -i inventory.txt configure-server.yml 
+
+            
+            
+  #           #exit 1
+  #     # Here's where you will add some code to rollback on failure      
+  #     - destroy_environments:
+  #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+  
   configure-infrastructure:
     docker:
-      # Docker image here that supports Ansible
-      # - image: python:3.7-alpine3.16 
-      # - image: python:3.9.1-alpine3.12  
-      - image: python:3.11-rc-alpine  
+      - image: cimg/base:stable
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
       - checkout
+      - install_awscli
+      - install_ansible
       - add_ssh_keys:
-          fingerprints: ["a3:c0:12:e5:23:e7:fa:23:10:a5:d9:ae:b6:99:35:80"] 
-          #
+          fingerprints: [b7:fa:6c:bb:e0:d3:80:7c:4b:65:a2:bc:76:47:2b:9b]
       - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            # Your code here
-            # apk add tar gzip 
-            # apk add --update ansible aws-cli
-            # apk add --update --no-cache tar gzip ansible awscli
-            # apk add --update tar gzip ansible
-            # pip install awscli
-            apk update 
-            apk upgrade
-            apk add --update ansible
-            apk --no-cache add python3 py3-pip
-            pip3 install --upgrade pip
-            pip3 install --no-cache-dir awscli
-            #exit 1
-            
+          at: ./workspace
       - run:
           name: Configure server
           command: |
-            # Your code here
-            echo NODE_ENV=production > ~/project/backend/.env
-            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> ~/project/backend/.env
-            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ~/project/backend/.env
-            echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> ~/project/backend/.env
-            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> ~/project/backend/.env
-            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> ~/project/backend/.env
-            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ~/project/backend/.env
-            echo TYPEORM_PORT=$TYPEORM_PORT >> ~/project/backend/.env
-            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ~/project/backend/.env
-            cat ~/project/backend/.env
+            aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters "Name=tag:aws:cloudformation:stack-name,Values=backend-udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --output text >> ~/project/.circleci/ansible/inventory.txt
+            cat ~/project/.circleci/ansible/inventory.txt
+            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt ~/project/.circleci/ansible/configure-server.yml
+          no_output_timeout: 30m
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/backend
 
-            cd ~/project/.circleci/ansible
-            ansible-playbook -i inventory.txt configure-server.yml 
-            
-            #exit 1
-      # Here's where you will add some code to rollback on failure      
       - destroy_environments:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-  
-
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
     
 
   run-migrations:
